# Generated by Django 4.1 on 2022-09-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_auto_20220830_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': True},
        ),
       
    ]
