# Generated by Django 4.1 on 2022-09-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_auto_20220910_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
    ]
